version: '3.1'
services:
  nginx:
    image: nginx:alpine
    restart: always
    environment:
      - TZ=Asia/Bangkok
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./config/:/etc/nginx/conf.d/
      - ./site:/var/www/html:ro
      - ./cf_ssl:/etc/ssl
    depends_on:
      - ghost

  db:
    image: mysql:8.0
    restart: always
    ports:
      - 0.0.0.0:3306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  ghost:
    image: ghost:5-alpine
    restart: always
    ports:
      - 0.0.0.0:2368:2368
    volumes:
      - ./ghost:/var/lib/ghost/content
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: ${DB_PASSWORD}
      database__connection__database: ghost
      url: ${DOMAIN}
    depends_on:
      - db

  iv-pb-api:
      build: involve-postback-api/.
      ports:
        - "0.0.0.0:3000:3000"

  # ksadb:
  #   image: mariadb:10.7
  #   container_name: ksadb
  #   restart: always
  #   environment:
  #     - TZ=Asia/Bangkok
  #     - MYSQL_DATABASE=ksadb
  #     - MYSQL_ROOT_PASSWORD=aa111111
  #   command:
  #     - '--character-set-server=utf8mb4'
  #     - '--collation-server=utf8mb4_unicode_ci'
  #   ports:
  #     - '3306:3306'
  #   volumes:
  #     - './database:/var/lib/mysql'
  #     - './init.sql:/docker-entrypoint-initdb.d/init.sql'

  # ksawp:
  #   image: wordpress:latest
  #   container_name: ksawp
  #   restart: always
  #   environment:
  #     - TZ=Asia/Bangkok
  #     - WORDPRESS_DB_HOST=ksadb:3306
  #     - WORDPRESS_DB_USER=root
  #     - WORDPRESS_DB_NAME=ksadb
  #     - WORDPRESS_DB_PASSWORD=aa111111
  #   ports:
  #     - '8080:80'
  #     - '8443:443'
  #   volumes:
  #     - ./php/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
  #     - ./storage/ksawp:/var/www/html
  #   depends_on:
  #     - ksadb