version: '3.5'
services:
  nginxdb:
    image: nginx:alpine
    container_name: nginxdb
    restart: always
    environment:
      - TZ=Asia/Bangkok
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./config/:/etc/nginx/conf.d/
      - ./site:/var/www/html:ro
    depends_on:
      - shortcache
      - shorturl
      # - code-server

  # code-server:
  #   image: lscr.io/linuxserver/code-server
  #   container_name: code-server
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - PASSWORD=aa111111
  #   volumes:
  #     - ./projects/:/home/coder/project
  #   ports:
  #     - 8443:8443
  #   restart: unless-stopped
    # user: ${CURRENT_UID:?"Please run as follows 'CURRENT_UID=$(id -u):$(id -g) docker-compose up'"}

  shortcache:
    container_name: shortcache
    image: redis:6.2-alpine
    restart: always
    ports:
      - '0.0.0.0:6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass $REDIS_PASSWORD
    volumes: 
      - shortcache:/data

  shorturl:
    image: docker-short-url
    container_name: shorturl
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
    restart: always
    ports:
      - '0.0.0.0:9808:9808'
    depends_on:
      - shortcache

volumes:
  shortcache:
    driver: local