version: '3.1'
services:
  # server:
  #   image: nginx:alpine
  #   restart: always
  #   environment:
  #     - TZ=Asia/Bangkok
  #   ports:
  #     - '80:80'
  #     - '443:443'
  #   volumes:
  #     - ./nginx/config/:/etc/nginx/conf.d/
  #     - ./site:/var/www/html:ro
  #     - ./cf_ssl:/etc/ssl

  server:
    image: caddy:latest
    volumes:
      - "./caddy/Caddyfile:/etc/caddy/Caddyfile"
      - "./site:/usr/share/caddy"
      - "./caddy/caddy_data:/data"
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"

  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  ghost:
    image: ghost:5-alpine
    restart: always
    ports:
      - 2368:2368
    volumes:
      - ./content:/var/lib/ghost/content
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: ${DB_PASSWORD}
      database__connection__database: ghost
      url: ${DOMAIN}
    depends_on:
      - db
      - server

  iv-pb-api:
    build: involve-postback-api/.
    restart: always
    ports:
      - "0.0.0.0:3000:3000"

  shlink:
    image: shlinkio/shlink:stable
    restart: always
    environment:
      - TZ="Asia/Bangkok"
      - DEFAULT_DOMAIN= ${SHLINK_DOMAIN}
      - IS_HTTPS_ENABLED=true
      # - GEOLITE_LICENSE_KEY=<GEOLITE_LICENSE_KEY>
      - DB_DRIVER=mysql
      - DB_USER=root
      - DB_NAME=shlink
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=3306
    depends_on:
      - db
    ports:
      - "0.0.0.0:8080:8080"