version: '3.5'
services:
  nginxdb:
    image: nginx:alpine
    container_name: nginxdb
    restart: always
    environment:
      - TZ=Asia/Bangkok
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./config/:/etc/nginx/conf.d/
      - ./site:/var/www/html:ro

  # code-server:
  #   image: codercom/code-server:latest
  #   volumes:
  #     - ./projects/:/home/coder/project:rw
  #   environment:
  #     - PASSWORD=aa111111

  code-server:
    image: lscr.io/linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD=aa111111 #optional
      # - HASHED_PASSWORD= #optional
      # - SUDO_PASSWORD=password #optional
      # - SUDO_PASSWORD_HASH= #optional
      # - PROXY_DOMAIN=code-server.my.domain #optional
      # - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      # - /path/to/appdata/config:/config
      - ./projects/:/home/coder/project:rw
    ports:
      - 8443:8443
    restart: unless-stopped


